// Lyceum Placements — Placement Management System
// Copyright © Bhanu Mendis - LGH IT
//
// Summary parity: the database must say about every case exactly what src/lib/summary.ts
// says. testdata/summary_parity.json (generated by `npm run parity:update`) carries 400
// generated case documents and the TypeScript answers at a fixed moment under two
// configurations; this test writes the documents through the real trigger and compares the
// derived columns, the case_state view and dashboard_summary field by field.
package integration

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"

	"lpl-api/internal/db"
)

type parityFixture struct {
	Now        string                               `json:"now"`
	Configs    map[string]json.RawMessage           `json:"configs"`
	Cases      []json.RawMessage                    `json:"cases"`
	Summaries  map[string]map[string]any            `json:"summaries"`
	States     map[string]map[string]map[string]any `json:"states"`
	Dashboards map[string]any                       `json:"dashboards"`
	Queries    []struct {
		Config string         `json:"config"`
		P      map[string]any `json:"p"`
		IDs    []string       `json:"ids"`
	} `json:"queries"`
}

// normal makes values comparable across JSON sources: instants as UTC milliseconds, numbers
// as float64.
func normal(v any) any {
	switch x := v.(type) {
	case string:
		if len(x) >= 20 && x[4] == '-' && x[10] == 'T' {
			if t, err := time.Parse(time.RFC3339Nano, x); err == nil {
				return t.UTC().Format("2006-01-02T15:04:05.000Z")
			}
		}
		return x
	case map[string]any:
		out := map[string]any{}
		for k, e := range x {
			out[k] = normal(e)
		}
		return out
	case []any:
		out := make([]any, len(x))
		for i, e := range x {
			out[i] = normal(e)
		}
		return out
	}
	return v
}

func diff(path string, want, got any, out *[]string) {
	want, got = normal(want), normal(got)
	switch w := want.(type) {
	case map[string]any:
		g, ok := got.(map[string]any)
		if !ok {
			*out = append(*out, fmt.Sprintf("%s: want object, got %v", path, got))
			return
		}
		keys := make([]string, 0, len(w))
		for k := range w {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			diff(path+"."+k, w[k], g[k], out)
		}
	case []any:
		g, ok := got.([]any)
		if !ok || len(g) != len(w) {
			*out = append(*out, fmt.Sprintf("%s: want %v, got %v", path, want, got))
			return
		}
		for i := range w {
			diff(fmt.Sprintf("%s[%d]", path, i), w[i], g[i], out)
		}
	default:
		if !reflect.DeepEqual(want, got) {
			*out = append(*out, fmt.Sprintf("%s: want %v, got %v", path, want, got))
		}
	}
}

func report(t *testing.T, what string, problems []string) {
	t.Helper()
	if len(problems) == 0 {
		return
	}
	if len(problems) > 25 {
		problems = append(problems[:25], fmt.Sprintf("… and %d more", len(problems)-25))
	}
	t.Errorf("%s disagrees with src/lib/summary.ts:\n  %s", what, strings.Join(problems, "\n  "))
}

func TestSummaryParityWithTypeScript(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("testdata", "summary_parity.json"))
	if err != nil {
		t.Fatal(err)
	}
	var fx parityFixture
	if err := json.Unmarshal(raw, &fx); err != nil {
		t.Fatal(err)
	}
	reset(t)
	super := bootstrapAdmin(t)
	system(t, func(ctx context.Context, ex db.Executor) error {
		for _, c := range fx.Cases {
			var head struct{ ID, Ref string }
			_ = json.Unmarshal(c, &head)
			if _, err := ex.Exec(ctx, "insert into public.cases (id, ref, rev, data) values ($1::text, $2::text, 1, $3::jsonb)", head.ID, head.Ref, string(c)); err != nil {
				return fmt.Errorf("%s: %w", head.ID, err)
			}
		}
		return nil
	})

	// 1. The derived columns.
	var problems []string
	system(t, func(ctx context.Context, ex db.Executor) error {
		var body string
		if err := ex.QueryRow(ctx, "select jsonb_object_agg(id, to_jsonb(c) - 'data')::text from public.cases c").Scan(&body); err != nil {
			return err
		}
		var got map[string]map[string]any
		if err := json.Unmarshal([]byte(body), &got); err != nil {
			return err
		}
		for id, want := range fx.Summaries {
			row := got[id]
			sub := map[string]any{}
			for k := range want {
				sub[k] = row[k]
			}
			diff(id, want, sub, &problems)
		}
		return nil
	})
	report(t, "case_derive", problems)

	for _, name := range []string{"standard", "tight"} {
		cfg := fx.Configs[name]
		system(t, func(ctx context.Context, ex db.Executor) error {
			_, err := ex.Exec(ctx, "update public.org_config set config = $1::jsonb where id = 'org'", string(cfg))
			return err
		})

		// 2. The case_state view at the fixture's moment.
		problems = nil
		system(t, func(ctx context.Context, ex db.Executor) error {
			if _, err := ex.Exec(ctx, "select set_config('lpl.now', $1::text, true)", fx.Now); err != nil {
				return err
			}
			var body string
			q := `select jsonb_object_agg(id, jsonb_build_object('breached', breached, 'due_soon', due_soon, 'docs_to_review', docs_to_review,
			        'gate_pending_now', gate_pending_now, 'gate_returned_now', gate_returned_now, 'profile_submitted_now', profile_submitted_now,
			        'hold_review_due', coalesce(hold_review_due, false), 'retention', retention, 'severity_rank', severity_rank, 'worst_days', worst_days))::text
			      from public.case_state`
			if err := ex.QueryRow(ctx, q).Scan(&body); err != nil {
				return err
			}
			var got map[string]any
			if err := json.Unmarshal([]byte(body), &got); err != nil {
				return err
			}
			for id, want := range fx.States[name] {
				diff(name+"."+id, want, got[id], &problems)
			}
			return nil
		})
		report(t, "case_state ("+name+")", problems)

		// 3. The dashboard, through the API as SUPER ADMIN.
		r := rpc(t, "dashboard_summary", super.Token, fmt.Sprintf(`{"p":{"now":%q}}`, fx.Now))
		expect(t, r, http.StatusOK, "")
		var got any
		if err := json.Unmarshal([]byte(r.Body), &got); err != nil {
			t.Fatal(err)
		}
		problems = nil
		diff("dashboard", fx.Dashboards[name], got, &problems)
		report(t, "dashboard_summary ("+name+")", problems)
	}
}
